#!/bin/sh
set -e
v=$(dpkg-parsechangelog -SVersion | sed -e 's/^[0-9]*://' -e 's/-[^-]*$//')
echo "src/                                             usr/src/linuwu-sense-$v/"
echo "Makefile                                         usr/src/linuwu-sense-$v/"
echo "debian/runtime/modprobe.d/linuwu-sense.conf      usr/lib/modprobe.d/"
echo "debian/runtime/modules-load.d/linuwu-sense.conf  usr/lib/modules-load.d/"
echo "debian/runtime/udev/63-linuwu-sense-perms.rules  usr/lib/udev/rules.d/"
echo "powersave/udev/64-acer-kbd-leds.rules          usr/lib/udev/rules.d/"
